version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl -fsS http://127.0.0.1:9000/minio/health/ready || exit 1',
        ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
